GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiWWluZyIsImlhdCI6MTY3OTI5NTg0OSwiZXhwIjoxNjc5Mjk1ODY0fQ.0UpMtidV9QxokIA2CULaoea7K9w0F1qVW1AdADjQkbQ
###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiWWluZyIsImlhdCI6MTY3OTI5NTU0Nn0.CmJ6hxkJov_D5u1uCyU3_1eBgPasjhv1qVZM7LKzTf8"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "Ying"
}

###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiWWluZyIsImlhdCI6MTY3OTI5NTgyNH0.rgrlpNa-AWhGF8_P3DHsiD1BSNhFvsPh_nKCuMRHTnQ"
}